reverted deletion of Examine Lint Changes workflow job

diff --git a/.github/workflows/analyze-project.yml b/.github/workflows/analyze-project.yml
--- a/.github/workflows/analyze-project.yml
+++ b/.github/workflows/analyze-project.yml
@@ -17,15 +17,22 @@ on:
   workflow_dispatch:
 
 jobs:
+
   lint:
     if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip-linting') }}
-    name: Dart Analyze
+    name: Generate Lint Reports
     runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        branch:
+          - main
+          - ${{ github.head_ref }}
 
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
         with:
+          ref: ${{ matrix.branch }}
           submodules: recursive
 
       - name: Set up Flutter
@@ -39,8 +46,73 @@ jobs:
       - name: Install dependencies
         run: flutter pub get
 
-      - name: Run analyzer
-        run: flutter analyze
+      - name: Lint the project
+        run: flutter analyze --no-fatal-infos --no-fatal-warnings --write=lints.txt
+
+      - name: Set sanitized branch name
+        id: sanitize
+        run: |
+          BRANCH="${{ matrix.branch }}"
+          SANITIZED_BRANCH="${BRANCH//\//-}"
+          echo "branch=$SANITIZED_BRANCH" >> $GITHUB_OUTPUT
+
+      - name: Upload lints artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: lints-${{ steps.sanitize.outputs.branch }}.txt
+          path: lints.txt
+          overwrite: true
+
+  examine-lint-changes:
+    if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip-linting') }}
+    name: Examine Lint Changes
+    runs-on: ubuntu-latest
+    needs: lint
+
+    steps:
+      - name: Sanitize branch name
+        id: sanitize
+        run: |
+          BRANCH="${{ github.head_ref }}"
+          SANITIZED_BRANCH="${BRANCH//\//-}"
+          echo "branch=$SANITIZED_BRANCH" >> $GITHUB_OUTPUT
+
+      - name: Download main branch artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: lints-main.txt
+          path: main-lints
+
+      - name: Download PR branch artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: lints-${{ steps.sanitize.outputs.branch }}.txt
+          path: pr-lints
+
+      - name: Compare lint results
+        run: |
+          ls -la
+          diff -u main-lints/lints.txt pr-lints/lints.txt | grep "^+" | grep -v "^+++" > lint-findings.txt || true
+          while IFS= read -r line; do
+            stripped_line="${line#+}"
+            if grep -Fxq "$stripped_line" main-lints/lints.txt; then
+              continue
+            else
+              echo "${stripped_line}" >> lint-changes.txt
+            fi
+          done < lint-findings.txt
+          if [ -s lint-changes.txt ]; then
+            echo "> [!CAUTION]" >> $GITHUB_STEP_SUMMARY
+            echo "> Found new lint issues in PR branch:" >> $GITHUB_STEP_SUMMARY
+            while read -r line; do
+              echo "> ${line}" >> $GITHUB_STEP_SUMMARY
+            done < lint-changes.txt
+            cat lint-changes.txt
+            echo -e "\033[0;31mError: No new linting errors may be merged with main.\033[0m"
+            exit 1
+          else
+            echo -e "\033[0;32mNo new lint issues found in PR branch.\033[0m"
+          fi
 
   test:
     name: Test
