test github-specific renderer

diff --git a/.github/workflows/unit-test.yml b/.github/workflows/unit-test.yml
--- a/.github/workflows/unit-test.yml
+++ b/.github/workflows/unit-test.yml
@@ -40,24 +40,24 @@ jobs:
       - name: Run tests
         run: |
           mkdir -p test-results
-          flutter test --no-fail-fast --file-reporter "json:test-results/flutter_test_results.json" || exit 0
+          flutter test --no-fail-fast -r github " || exit 0
 
       # - name: Process test results
       #   run: |
       #     echo "### Flutter Test Results" > test-results/report.md
       #     echo "---" >> test-results/report.md
           
-      #     # Extract test results and format them for the comment
-      #     jq -r '.[] | select(.type == "testDone") | 
-      #       if .result == "success" then
-      #         "✅ " + .testName + "\n"
-      #       elif .result == "failure" then
-      #         "❌ " + .testName + "\n"
-      #       elif .result == "skipped" then
-      #         "⏭️ " + .testName + "\n"
-      #       else
-      #         "⚠️ " + .testName + "\n"
-      #       end' test-results/flutter_test_results.json >> test-results/report.md
+          # Extract test results and format them for the comment
+          # jq -r '.[] | select(.type == "testDone") | 
+          #   if .result == "success" then
+          #     "✅ " + .testName + "\n"
+          #   elif .result == "failure" then
+          #     "❌ " + .testName + "\n"
+          #   elif .result == "skipped" then
+          #     "⏭️ " + .testName + "\n"
+          #   else
+          #     "⚠️ " + .testName + "\n"
+          #   end' test-results/flutter_test_results.json >> test-results/flutter_test_results.md
           
       #     # Add summary
       #     echo "---" >> test-results/report.md
@@ -94,12 +94,12 @@ jobs:
           name: test-results
           path: test-results/
           
-      - name: Check for test failures
-        run: |
-          FAILED=$(jq -r '.[] | select(.type == "testDone") | select(.result == "failure") | .result' test-results/flutter_test_results.json | wc -l)
-          if [ $FAILED -gt 0 ]; then
-            exit 1
-          fi
+      # - name: Check for test failures
+      #   run: |
+      #     FAILED=$(jq -r '.[] | select(.type == "testDone") | select(.result == "failure") | .result' test-results/flutter_test_results.json | wc -l)
+      #     if [ $FAILED -gt 0 ]; then
+      #       exit 1
+      #     fi
 
   build:
     runs-on: ubuntu-latest
